# -*- coding: utf-8 -*-
"""Telcochurn-logistic-regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16TMupv95h_0ar-lkX_347byr7y7IEcdU
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
path = "/content/drive/MyDrive/Academia/Telco-Customer-Churn.csv"
df = pd.read_csv(path)
df.head(5)

import numpy as np

# 0) Convert to NumPy
data = df.values  # object dtype is expected for Telco
print("data.shape:", data.shape)
print("data.dtype:", data.dtype)

# 1) Column names (so you can map indices to features)
cols = df.columns.to_list()
for i, c in enumerate(cols):
    print(i, c)

# 2) Quick peek: first 5 rows (NumPy view)
print("\nFirst 5 rows (raw):")
print(data[:5, :])

# 3) Check for empty strings (common in TotalCharges)
empty_str_count = np.sum(data == "")
print("\nEmpty-string cells count:", empty_str_count)
# Per-column empty-string counts (helps locate the problematic column)
empty_by_col = np.array([np.sum(data[:, j] == "") for j in range(data.shape[1])])
print("\nEmpty strings per column (index, name, count):")
for j, cnt in enumerate(empty_by_col):
    if cnt > 0:
        print(j, cols[j], cnt)

# 4) Check missing values from pandas (NaN) reflected in NumPy
# NaNs won't compare equal to anything, so do column-wise using pandas mask:
nan_by_col = df.isna().sum().values
print("\nNaNs per column (index, name, count):")
for j, cnt in enumerate(nan_by_col):
    if cnt > 0:
        print(j, cols[j], int(cnt))

# 5) Identify likely ID + target columns (verify by values)
print("\nPotential ID column sample (col 0):", data[:5, 0])
print("Potential target column sample (last col):", data[:10, -1])
print("Unique target values:", np.unique(data[:, -1]))

# 6) Inspect each column’s type/uniques (trimmed)
# Useful to decide: binary categorical vs multi-class vs numeric stored as string
print("\nColumn summaries (index, name, unique_count, sample_uniques):")
for j in range(data.shape[1]):
    col = data[:, j]
    # For large unique columns (like customerID), don't print all uniques
    uniques = np.unique(col)
    sample = uniques[:5]
    print(j, cols[j], len(uniques), sample)

import numpy as np

# 7) Locate numeric-looking columns that are stored as strings (object)
# Attempt numeric conversion on each column and see which succeed
print("\nNumeric-convertibility check (index, name, convertible_ratio):")
m = data.shape[0]
for j in range(data.shape[1]):
    col = data[:, j]

    # Treat blanks as NaN for convertibility test
    col_clean = np.where(col == "", np.nan, col)

    # Try convert: valid numbers -> float, invalid -> nan
    conv = np.array([np.nan if x is np.nan else (float(x) if str(x).replace('.','',1).isdigit() else np.nan)
                     for x in col_clean], dtype=float)

    ratio = np.mean(~np.isnan(conv))
    # Print only columns with high convertibility (likely numeric features)
    if ratio > 0.95:
        print(j, cols[j], f"{ratio:.3f}")

# 8) Class balance check (after encoding target) - still part of inspection
y_raw = data[:, -1]
y = np.where(y_raw == "Yes", 1, 0)
pos = np.mean(y == 1)
neg = np.mean(y == 0)
print("\nClass balance:")
print("Churn=1 (Yes):", pos)
print("Churn=0 (No): ", neg)

#drop customer id column
data = data[:, 1:]

#seperate features from target column
X_raw = data[:, :-1]
y_raw = data[:, -1]

y = np.where(y_raw == "Yes", 1, 0)
print(np.unique(y))   # should be [0 1]

cols_after_drop_id = df.columns.to_list()[1:]   # drop customerID
feature_names = cols_after_drop_id[:-1]         # drop Churn

for i, c in enumerate(feature_names):
    print(i, c)

total_index = 18 # 'TotalCharges' column after dropping 'customerID'
total = X_raw[:, total_index]

# Replace empty strings and strings containing only spaces with '0'
total = np.where(np.char.strip(total.astype(str)) == "", "0", total)
total = total.astype(float)

X_raw[:, total_index] = total

tenure_index = 4
monthly_index = 17

X_raw[:, tenure_index] = X_raw[:, tenure_index].astype(float)
X_raw[:, monthly_index] = X_raw[:, monthly_index].astype(float)

def one_hot_encode(column):
    unique_vals = np.unique(column)
    encoded = np.zeros((len(column), len(unique_vals)))

    for i, val in enumerate(unique_vals):
        encoded[:, i] = (column == val).astype(int)

    return encoded

encoded_columns = []

for j in range(X_raw.shape[1]):
    col = X_raw[:, j]

    # Try numeric conversion
    try:
        col_numeric = col.astype(float)
        encoded_columns.append(col_numeric.reshape(-1, 1))

    except:
        # If conversion fails → categorical → one-hot encode
        unique_vals = np.unique(col)
        encoded = np.zeros((len(col), len(unique_vals)))

        for i, val in enumerate(unique_vals):
            encoded[:, i] = (col == val).astype(int)

        encoded_columns.append(encoded)

X = np.hstack(encoded_columns)

X = X.astype(float)
y = y.astype(int)

print(X.shape)
print(X.dtype)

print(y.shape, y.dtype)
print(np.unique(y, return_counts=True))
print("NaNs:", np.isnan(X).sum())
print("Infs:", np.isinf(X).sum())
col_std = X.std(axis=0)
const_cols = np.where(col_std == 0)[0]
print("Constant columns:", const_cols, "count:", len(const_cols))
print("X min/max:", X.min(), X.max())
print("First row:", X[0])

# 2) Train/test split (80/20)
n = X.shape[0]
rng = np.random.default_rng(42)
indices = rng.permutation(n)
split = int(0.8 * n)

train_idx = indices[:split]
test_idx  = indices[split:]

X_train, X_test = X[train_idx], X[test_idx]
y_train, y_test = y[train_idx], y[test_idx]

print("X_train:", X_train.shape, "X_test:", X_test.shape)
print("y_train:", y_train.shape, "y_test:", y_test.shape)

# 3) Standardize using TRAIN only
mu = X_train.mean(axis=0)          # (d,)
sigma = X_train.std(axis=0)        # (d,)

# Guard against constant columns
sigma_safe = sigma.copy()
sigma_safe[sigma_safe == 0] = 1.0

X_train_s = (X_train - mu) / sigma_safe
X_test_s  = (X_test  - mu) / sigma_safe

print("Any NaN in X_train_s?", np.isnan(X_train_s).any(), "Any inf?", np.isinf(X_train_s).any())
print("Any NaN in X_test_s?",  np.isnan(X_test_s).any(),  "Any inf?", np.isinf(X_test_s).any())

print("X_train_s:", X_train_s.shape, "X_test_s:", X_test_s.shape)
print("y_train:", y_train.shape, "y_test:", y_test.shape)

print("NaN train:", np.isnan(X_train_s).any(), "Inf train:", np.isinf(X_train_s).any())
print("NaN test :", np.isnan(X_test_s).any(),  "Inf test :", np.isinf(X_test_s).any())

print("Class balance train:", np.unique(y_train, return_counts=True))
print("Class balance test :", np.unique(y_test,  return_counts=True))

def sigmoid(z):
  g = 1/(1+np.exp(-z))
  return g

w = np.zeros(X_train_s.shape[1])
b = 0.0
z = X_train_s @ w + b
y_hat = sigmoid(z)
print(y_hat[:5])
print(y_hat.shape)

def compute_cost_logistic(X_train_s, y_train, w, b):
    cost = 0.0
    z = X_train_s @ w + b
    y_hat = sigmoid(z)
    eps = 1e-15
    y_hat = np.clip(y_hat, eps, 1-eps)
    cost = -np.mean(y_train * np.log(y_hat) + (1 - y_train) * np.log(1 - y_hat))
    return cost

c = compute_cost_logistic(X_train_s, y_train, w, b)
print(c)

def gradient(X_train_s, y_train, w, b):
  m = X_train_s.shape[0]
  z = X_train_s @ w + b
  y_hat = sigmoid(z)
  error = y_hat - y_train
  dw = 1/m * X_train_s.T @ error
  db = 1/m * np.sum(error)
  return dw, db

w = np.zeros(X_train_s.shape[1])
b = 0.0
dw, db = gradient(X_train_s, y_train, w, b)
print(dw.shape)
print(db)

def fit_logreg(X_train_s, y_train, lr=0.1, iters=2000):
  w=np.zeros(X_train_s.shape[1])
  b=0.0
  losses = []
  for i in range(iters):
    dw, db = gradient(X_train_s, y_train, w, b)
    w -= lr * dw
    b -= lr * db
    if i % 100 == 0:
      losses.append(compute_cost_logistic(X_train_s, y_train, w, b))
  return w, b, losses

w, b, losses = fit_logreg(X_train_s, y_train, lr=0.1, iters=2000)
print("first 3:", losses[:3])
print("last 3:", losses[-3:])

p_test = sigmoid(X_test_s @ w + b)  # shape (m_test,)

def f1_at_threshold(y_true, p, t):
    pred = (p >= t).astype(int)


    tp = np.sum((y_true==1) & (pred==1))
    fp = np.sum((y_true==0) & (pred==1))
    fn = np.sum((y_true==1) & (pred==0))


    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall    = tp / (tp + fn) if (tp + fn) > 0 else 0.0


    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0
    return f1, precision, recall

thresholds = np.linspace(0.0, 1.0, 101)

best_t = None
best_f1 = -1.0
best_pr = None
best_rc = None

for t in thresholds:
    f1, pr, rc = f1_at_threshold(y_test, p_test, t)
    if f1 > best_f1:
        best_f1 = f1
        best_t = t
        best_pr = pr
        best_rc = rc

f1_05, pr_05, rc_05 = f1_at_threshold(y_test, p_test, 0.5)

print("Best threshold:", best_t)
print("Best F1:", best_f1, "Precision:", best_pr, "Recall:", best_rc)
print("At t=0.5  F1:", f1_05, "Precision:", pr_05, "Recall:", rc_05)